### PR TITLE
Removed the checking for 'validate_' in the name of the custom rules, since it's no longer in use.

### PR DESCRIPTION
**Pull request by oxyzero**

### CODE REVIEW

**Comment by alexgarrett** [comment]
Thanks for the PR, I'll check this out tonight :+1:

**Comment by alexgarrett** [comment]
Just had a look at this.

Did you know that the validate_ methods are used for the extending of the Violin class? https://github.com/alexgarrett/violin/blob/master/examples/extending.php

**Comment by oxyzero** [comment]
Oh right, I completely missed that!
I was thinking the point of the 'validate_' was for adding custom rules just like this:
https://github.com/alexgarrett/violin/blob/master/examples/custom_rule.php

Does the error structure work the way you wanted though?

**Comment by alexgarrett** [comment]
Ah yes sorry, should have mentioned. The error stuff looks good :)

**Comment by oxyzero** [comment]
I fixed my previous commit where I deleted the 'validate_' methods.

Also, in the error structure we could remove the first argument into the field name only. What I mean is, at the moment, we have the rule name repeating twice (on the field name, and on the arguments). The problem is we needed to add the rule name again for the sake of the vsprintf() method.
When we have: "Allow errors to be defined with {field} and {value} rather than %s's for greater flexibility." implemented this should be an easy fix without the need to actually add the rule name back in. Unless there is no problem with it getting repeated.

**Comment by alexgarrett** [comment]
Awesome, thanks for that.

If you could fix up the conflicts I can get this merged, and then raise an issue or PR for the other thing and we can discuss it?

**Pull request closed without merging**
