### PR TITLE
Added Violin\Support\MessageBag that handles the message output. Added v...

### PR DESCRIPTION
**Pull request by oxyzero**
...ery basic unit testing. Added support to get multiple values from rule messages for rules that have multiple arguments, and included the Between rule.

@alexgarrett So, I wanted to discuss some changes I've made today into the project.
I've implemented some basic unit testing into the project as asked for in Issue #6.

I also added another rule: Between. This rule checks if a number is within an closed interval. It's pretty straight forward.

In regards to the error structure, I managed to develop the MessageBag. I created the messages() method in Violin\Validator\Validator which picks the errors from the errors array and generates the messages and then returns an instance of Violin\Support\MessageBag
In this class we can define the methods you were referring, so that we can easily manipulate error message output.

 I also changed the way that we can format rule messages. I've created an array in Violin\Validator\Validator that has the default value of:
 ```php 
public $format = ['{field}', '{input}', '{value}']; 
```
And I also added the replace() method. What this method does is it looks for the format in the string and replaces it with the arguments of the rule.
Since Violin supports multiple parameters for rules definitions, I had to hack the replace() method a bit, therefore it kinda looks a little bit messy. What I am talking about is this:
```php
if (count($arguments) > 3) {
            // If the arguments array is bigger than the format
            // array, then we need to consider that the rule has
            // multiple paramaters.
            $format = $this->format;

            for ($i = 2; $i < count($arguments); $i++) {
                $format[] = '{value:' . ($i - 1) . '}';
            }

            return str_replace($format, $arguments, $message);
        }
```
So I am assuming that the default formatting for Violin should be 3 elements (the field, the input, and the value), so if the number of arguments a rule has is bigger than 3, we need to handle the format for these multiple arguments.
What I did was to add the rest of the values into a new array and replace the string with the arguments based on that new format so that we can do:
```php
$v->addRuleMessage('between', '{field} must be between [{value}, {value:1}].');

$v->validate('age' => 20, ['age' => 'between(10, 20)']);
```

What do you think about the changes I've made? If anything is unclear let me know!

### CODE REVIEW

**Comment by alexgarrett** [comment]
This is absolutely fantastic, thank you. I'll have a good review of this later on when I can pull down your branch :+1:

**Comment by djangokillen** [comment]
Really nice, but I find it a little weird that we wrap the between rule output message in an array like this: [{value}, {value:1}]. Isn't it a little bit more nice looking if we don't have that array?

**Comment by oxyzero** [comment]
In the example above we have this:
```php
$v->addRuleMessage('between', '{field} must be between [{value}, {value:1}].');
```

It may generate some confusion with the [ ] because it seems like it's an array. I just used the brackets to simulate intervals.
However, we can just call them like this:
```php
$v->addRuleMessage('between', '{field} must be between {value} and {value:1}.');
```

**Comment by djangokillen** [comment]
Great, Oxyzero. That actually confused me a bit :)

**Comment by alexgarrett** [comment]
This is really great, can't thank you enough. I'll get Travis set up to run your unit tests.

:+1:

**Pull request merged**
