### PR TITLE
Possibility to verify certain rules

### PR DESCRIPTION
**Pull request by Lowseling**
@alexgarrett I've made a small change to the passes() function on the Violin class. This change gives the opportunity to verify only certain rules. This is usefull for example when you need to do certain actions when only some rules fails.

What do you think? :)

P.S. - Sorry for my english!

### CODE REVIEW

**Comment by pedzed** [comment]
Thanks for submitting a PR! Don't worry about your English. As long as it is understandable and your tried your best, nobody would mind.

Next time though, please be more descriptive in your commit message(s). "Update X" can be anything. I know it can be hard to give it a good name, but it helps to maintain the code better (i.e. checking the history).

My personal opinion is that this PR should be rejected, because I don't see any use of it. If you add certain rules, it means that you want to validate them. If you don't want to validate them, then why would you add it in in the first place? Perhaps I would change my mind if you can explain why this may be useful.

You should make your code [PSR-2 compliant](http://www.php-fig.org/psr/psr-2/). The way you put your `else`'s for example, will not be accepted. 

Also, you should add unit test(s) that verify that some given input, gives you some expected output.

**Comment by alexgarrett** [comment]
@Lowseling Did you see @pedzed's comments?

**Comment by Lowseling** [comment]
@alexgarrett @pedzed Oh sorry, I actually forgot to answer! For PSR standard I actually started this month to follow it because I always prefer to use my own syntax, but I started to use it for open source projects. I wrote this function because sometimes instead of verifying all the rules together I need to handle it one by one. This is a personal preference, I pulled this because I thought someone can find it usefull, but this is your choice :)

**Comment by alexgarrett** [comment]
@Lowseling Thanks for getting back to me.

I think at this point in time I agree with @pedzed so I'll close the request. I can kinda see what you're doing, but the implementation is a little verbose and since it's not a common issue, we'll leave it. Feel free to contribute further if you ever want to, though!

**Pull request closed without merging**
